update

diff --git a/rtfm b/rtfm
--- a/rtfm
+++ b/rtfm
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 set -euo pipefail
 declare -- PRG0 PRGDIR PRG
-
 PRG0="$(readlink -f -- "$0" 2>/dev/null || echo "$0")"
 PRGDIR="${PRG0%/*}"
 PRG="${PRG0##*/}"
@@ -60,25 +59,33 @@ main() {
   while (($#)); do
     case $1 in
       -r|--rebuild-lists)
-              rebuild_help_lists
-              exit 0
+          rebuild_help_lists
+          exit 0
               ;;
-      update|--install|--update)
-              sudo -ln &>/dev/null || {
-                 >&2 echo "$PRG: Install/Update requires root, or non-interactive sudo privileges."
-                 exit 1
-              }
-              sudo -n "$0" installupdate $( ((VERBOSE)) && echo '--verbose' ); exit
-              ;;
+      --install|--update)
+          sudo -ln &>/dev/null || {
+             >&2 echo "$PRG: Install/Update requires root, or non-interactive sudo privileges."
+             exit 1
+          }
+          local -- install_rtfm=/tmp/install_update_rtfm.sh
+          {  echo '#!/bin/bash'
+             echo 'set -euo pipefail'
+             declare -p PRGDIR PRG VERBOSE
+             declare -pf install_update_rtfm rebuild_help_lists
+             echo 'install_update_rtfm'
+          } >"$install_rtfm"
+          chmod 700 "$install_rtfm"
+          exec sudo "$install_rtfm"; exit 1
+          ;;
       -q|--quiet)
-              VERBOSE=0
-              ;;
+          VERBOSE=0
+          ;;
       help|-h|--help)
-              usage 0 ;;
-      -*)     >&2 echo "$PRG: Invalid option '$1'" ;;
-      *)      [[ -n $cmd ]] && { >&2 echo "$PRG: Too many arguments"; exit 22; }
-              cmd="$1"
-              ;;
+          usage 0 ;;
+      -*) >&2 echo "$PRG: Invalid option '$1'" ;;
+      *)  [[ -n $cmd ]] && { >&2 echo "$PRG: Too many arguments"; exit 22; }
+          cmd="$1"
+          ;;
     esac
     shift
   done
@@ -128,7 +135,7 @@ rebuild_help_lists() {
   # chmod 664 "$PRGDIR"/builtin.list
 
   ((VERBOSE)) && echo "$PRG: Updating 'tldr' command list"
-  find "$HOME"/.local/share/tldr/pages.en/common -type f -exec basename -s '.md' {} \; 2>/dev/null \
+  find /usr/local/share/tldr -type f -exec basename -s '.md' {} \; 2>/dev/null \
       | sort -u \
       | grep -v ^$ \
     >"$PRGDIR"/tldr.list || true
@@ -152,20 +159,18 @@ rebuild_help_lists() {
 }
 
 install_update_rtfm() {
-  [[ ${1:-} == '--verbose' ]] || VERBOSE=0
-
   if ! command -v git >/dev/null; then
     ((VERBOSE)) && echo "$PRG: Installing git..."
     /usr/bin/apt-get -qq update || true
     /usr/bin/apt-get -qq install git || true
   fi
 
-  local -- REPOBASE BASEDIR repo installupdate='Installing'
-
+  # already installed?
+  local -- installupdate='Installing'
   [[ -f /usr/local/share/rtfm/rtfm ]] && installupdate='Updating'
 
-  REPOBASE=https://github.com/Open-Technology-Foundation
-
+  local -- REPOBASE=https://github.com/Open-Technology-Foundation
+  local -- BASEDIR repo
   for repo in tldr md2ansi rtfm; do
     ((VERBOSE)) && echo "$PRG: $installupdate $REPOBASE/$repo"
     BASEDIR=/usr/local/share/"$repo"
@@ -194,14 +199,6 @@ install_update_rtfm() {
   ((VERBOSE)) && echo "$PRG: $installupdate complete"
   exit 0
 }
-
-# catch install/update command
-if ((EUID==0)); then
-  if [[ "${1:-}" == installupdate ]]; then
-    install_update_rtfm "${@:2}"
-    # Not necessary to call exit here as the function already does
-  fi
-fi
 
 main "$@"
 
